Entire code for Gutenberg Slideshow block
aapatre/fun-slides pull request #2
Opened 2021-12-01 07:27 UTC by aapatre

## Carousel Libraries Used:

- React Slick (for back-end)
 
- Slick (the original slick library for the front-end)

- Slick Theme (for the front-end CSS)

## Additional Notes:

- If slides are added in the back-end but the media isn't selected, the entire slide is scrapped on the front-end 

## Screenshots

### Front-end

<img src="https://user-images.githubusercontent.com/20199688/144190634-3327fef1-aa87-45be-8193-b77f4db8253e.png" height="250px" />

### Backend

#### Slide Link UI (to add links to the slide media)

<img src="https://user-images.githubusercontent.com/20199688/144190671-2f360460-f8b6-4f0b-bb8e-b8f8172b3485.png" height="250px" />

#### Rich Text Editor

<img src="https://user-images.githubusercontent.com/20199688/144190738-347deb26-4d8d-441a-890d-fbbbc9bbbdde.png" height="250px" />

#### Media Placeholder / Slide Media Uploader

<img src="https://user-images.githubusercontent.com/20199688/144190697-5746c57c-a25f-4524-bf2c-6180ac3ba64a.png" height="250px" />

## Fixes/Closes

Closes: #1

2021-12-01 11:59 UTC, yahilmadakiya requested changes
Overall looks good. Just need to follow proper spacing.

2021-12-01 11:59 UTC, yahilmadakiya commented on fun-slides.php
> +add_action('wp_enqueue_scripts', 'enqueue_slider_frontend_script');
follow phpcs.
add proper spacing before after ( )

2021-12-01 11:59 UTC, yahilmadakiya commented on src/edit.js
> +						help={ __( 'Display the left-right navigation arrows to change slides on front-end?', 'fun-slides' ) }
Remove ? from label, help string.

2021-12-01 11:59 UTC, yahilmadakiya commented on src/edit.js
> +					<div>Add a slide with the <span class="dashicons dashicons-plus"></span> icon on block toolbar</div>
instead of adding slider from block toolbar can we display media placeholder if slideshow in empty?
we can have first item of object empty by default.

2021-12-01 11:59 UTC, yahilmadakiya commented on src/save.js
> +	console.log(frontend_slideshow);
Remove

2021-12-01 11:59 UTC, yahilmadakiya commented on src/save.js
> +									console.log(slide.slideLink.title)
??

2021-12-01 11:59 UTC, yahilmadakiya commented on src/editor.scss
> +	margin-left: auto;
If there is any common style in style.scss and editor.scss you can import style.scss here and add extra style.

2021-12-01 11:59 UTC, yahilmadakiya commented on slider-frontend.js
> +jQuery(document).ready(function(){
Can you confirm If there is more than one slider being used in page is it working fine?

2021-12-01 11:59 UTC, yahilmadakiya commented on src/edit.js
> +		setAttributes( { slideTimer: slideTimerValue } );
Can we move setAttributes onChange itself?

2021-12-01 11:59 UTC, yahilmadakiya commented on src/edit.js
> +						onChange={ setShowSliderDots }
```suggestion
						onChange={ () => setAttributes( { showSliderDots: ! showSliderDots } )
```

2021-12-01 11:59 UTC, yahilmadakiya commented on src/edit.js
> +					<CheckboxControl
We can use `ToggleControl` instead of `CheckboxControl`. Looks good.

2021-12-01 12:30 UTC, aapatre commented on src/save.js
> +									console.log(slide.slideLink.title)
That must have been a test... removed it

2021-12-01 12:31 UTC, aapatre commented on src/edit.js
> +						onChange={ setShowSliderDots }
Got it!

2021-12-01 14:41 UTC, aapatre commented on slider-frontend.js
> +jQuery(document).ready(function(){
I see, all sliders are being paused... I will look into it

2021-12-01 14:55 UTC, aapatre commented on src/editor.scss
> +	margin-left: auto;
I've used different classes and slightly different HTML structure for the editor and front-end so I've kept separate files.

2021-12-01 15:35 UTC, aapatre commented on fun-slides.php
> +add_action('wp_enqueue_scripts', 'enqueue_slider_frontend_script');
The current PHPCS configs are actually throwing errors when I keep space around parentheses.

![image](https://user-images.githubusercontent.com/20199688/144260265-a2362db3-41ad-44a6-843c-d365634b6de6.png)

Without spacing:
![image](https://user-images.githubusercontent.com/20199688/144260952-50369ee6-4847-43a0-bc0b-a88ab954f55f.png)

2021-12-07 06:15 UTC, yahilmadakiya commented on slider-frontend.js
> +function getClickedSlideshowObjIndex( clickedObj, classNameOfObjs ) {
**Suggestion**

Seems link it's more complicated logic for simple solution.
you can try something like below to allow multiple slide on same page.
https://github.com/penske-media-corp/pmc-larva/blob/master/packages/larva-js/src/interface/Flickity/index.js

2021-12-07 06:18 UTC, yahilmadakiya approved these changes

2021-12-07 06:18 UTC, yahilmadakiya commented on src/edit.js
> +	}
Can we detele this?

2021-12-14 05:36 UTC, aapatre commented on slider-frontend.js
> +function getClickedSlideshowObjIndex( clickedObj, classNameOfObjs ) {
Got it! I went through the reference code and Flickity's site, the code only initializes all instances of Flickity on the page. But the code that I wrote is not only for initializing, but also for pausing/un-pausing the autoplay of specific slider when a video is being played.

In my old code, all slider instances were being paused after playing a video of any slider instance. And all sliders were being autoplayed after the video was paused (irrespective of their autoplay settings). So the new code fixes that...

Please let me know about another reference code in case there is a simpler solution for the above :)

2021-12-14 05:40 UTC, yahilmadakiya commented on slider-frontend.js
> +function getClickedSlideshowObjIndex( clickedObj, classNameOfObjs ) {
The example is just to understand how to initialize script for different elements and keep changes for that slider only.
At [line:4](https://github.com/penske-media-corp/pmc-larva/blob/master/packages/larva-js/src/interface/Flickity/index.js#L4) it gets each slide and then initialize slider [one-by-one](https://github.com/penske-media-corp/pmc-larva/blob/master/packages/larva-js/src/interface/Flickity/index.js#L6) inside that loop you can add your play/paush logic.

2022-03-30 04:33 UTC, merged